import { loader, type InferPageType } from 'fumadocs-core/source';
// This file is generated by fumadocs-mdx
import { docs } from '.source/server';

export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
});

export type Page = InferPageType<typeof source>;

export async function getLLMText(page: Page): Promise<string> {
  const processed = await page.data.getText('processed');
  return `---
title: ${page.data.title}
description: ${page.data.description ?? ''}
url: https://moltbet.xyz/docs/${page.slugs.join('/')}
---

${processed}`;
}
